on: 
  workflow_dispatch: 
        
jobs:
  # This workflow contains a single job called "build"
  build-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: datapractice.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./containerd
          push: true
          tags: datapractice.azurecr.io/runner-cont:latest
